package security3.common;

/**
 * Strategy interface for providing error message classes with a base set of attributes.
 * Based on recommendations from RFC 7807.
 *
 */
public interface VSErrorMessage {

    /**
     * A URI reference that identifies the problem type.
     *
     * @return the problem type.
     */
    String getType();

    /**
     * A short, human-readable summary of the problem type.
     *
     * @return summary of the problem type.
     */
    String getTitle();

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     *
     * @return the HTTP status code.
     */
    Integer getStatus();

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     *
     * @return explanation specific to this problem.
     */
    String getDetail();

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * It may or may not yield further information if dereferenced.
     *
     * @return URI reference to the specific problem occurrence.
     */
    String getInstance();

 }
